### ISSUE TITLE
Please add clockwork 5 support in composer

### ISSUE THREAD

**Issue by tck** [hannesvdvreken/guzzle-clockwork#11]

**Comment by hannesvdvreken** [comment]
For this I will need to do some testing, and for that I will need to make some time. Please hold on.

**Comment by hannesvdvreken** [comment]
Sorry for the long wait. 

https://github.com/hannesvdvreken/guzzle-clockwork/releases/tag/4.0.0-RC1

Please test and verify. If you agree, I can tag 4.0.0 final.
