### ISSUE TITLE
Could you please update the documentation?

### ISSUE THREAD

**Issue by YunYami** [hannesvdvreken/guzzle-clockwork#14]
It seems to be outdated. Some classes no longer exist. 
I am currently using Guzzle 7.2, and I couldn't find GuzzleHttp\Profiling\Clockwork\Profiler, nor GuzzleHttp\Profiling\Clockwork\Support\Laravel\ServiceProvider.

**Comment by hannesvdvreken** [comment]
Correct.

The beforementioned classes can be found here: https://github.com/hannesvdvreken/guzzle-profiler. This package works together with that package. So you can profile in both Clockwork as well as Debugbar.

I'm no longer active in the PHP community. If you know someone who would be interested to take over the active maintenance of this package, feel free to let me know!
