### ISSUE TITLE
Latest version compatibility

### ISSUE THREAD

**Issue by mattgreen110** [hannesvdvreken/guzzle-clockwork#3]
Any plans to make this work with the latest version of Guzzle?

**Comment by JosephSilber** [comment]
@hannesvdvreken What about Guzzle 5 and Laravel 5?

**Comment by hannesvdvreken** [comment]
@JosephSilber I'll make L4, Guzzle v5 compatible version and a L5, Guzzle v5 compatible version later today.

**Comment by hannesvdvreken** [comment]
@JosephSilber Can you check? Version 0.3.0 should be able to work with Guzzle v5 and it should be compatible with Laravel 5.

**Comment by JosephSilber** [comment]
https://github.com/hannesvdvreken/guzzle-clockwork/blob/master/composer.json#L19

**Comment by hannesvdvreken** [comment]
That's a dev dependency, it shouldn't keep you from installing this in a L5 application.
