### ISSUE TITLE
New major version for clockwork 2

### ISSUE THREAD

**Issue by s00d** [hannesvdvreken/guzzle-clockwork#5]

**Comment by hannesvdvreken** [comment]
Good idea. Will upgrade Guzzle as well.

**Comment by hareland** [comment]
Is this coming any time soon @hannesvdvreken ?

**Comment by hannesvdvreken** [comment]
in retrospect: no upgrade of guzzle needed.

**Comment by hannesvdvreken** [comment]
@hareland Lost track of this, tbh. Feel free to create PR?

**Comment by hannesvdvreken** [comment]
@hareland took a quick look at https://github.com/itsgoingd/clockwork/blob/v2.0.1/CHANGELOG.md. Doesn't look like a difficult upgrade for us. Maybe clone it, update composer.json and test it out. Should be easy.

**Comment by hareland** [comment]
@hannesvdvreken I am more looking for a version to support Clockwork ^2 out of the box. 

Right now people are bound to use old versions of Clockwork, and as many people use Postman, this creates a lots of headaches when wanting to inspect postman requests - especially now after Google Chrome removes support for Chrome apps.

Thats more what i am asking, as Clockwork 2 is not supported with this package

**Comment by hannesvdvreken** [comment]
Thanks. Almost ready to release it. Just gonna tag it 1.1.0 because I still allowed clockwork v 1.4.0 and up to be used so I didn't need a full new major version.

**Comment by hannesvdvreken** [comment]
Done https://github.com/hannesvdvreken/guzzle-clockwork/releases/tag/1.1.0
