### ISSUE TITLE
New Major release for Clockwork

### ISSUE THREAD

**Issue by ragingdave** [hannesvdvreken/guzzle-clockwork#8]
Clockwork has recently released version 3.0 and is targeting a 4.0 release in the spring-ish.

This is a fairly useful package, that I would like to continue using, but I am unable to as the dependency tree prevents it

**Comment by hannesvdvreken** [comment]
Hi Dave,

Thanks for keeping me posted. I've gone through Clockwork's changes and I don't see any breaking changes for us. So I'm gonna create a dev version to support 3.0.0 and up so you can test it.

**Comment by hannesvdvreken** [comment]
Alright, Dave,

You can change your dependency on "hannesvdvreken/guzzle-clockwork" to `dev-master` and check it out. Lemme know if it works, or not.

**Comment by hannesvdvreken** [comment]
@ragingdave any update?

**Comment by ragingdave** [comment]
sorry I will take a peek today and see if that is working, got sidetracked.

**Comment by ragingdave** [comment]
Finally got a chance to test it and it seems to be working. Only caveat I will add is that I'm not using your built in ServiceProvider as I have to configure Guzzle from another service provider for some SDK usage I have. I do use the HandlerStack resolving event verbatim internally, so while it's not quite an apples to apples test as far as a Gala to Fuji apple test....it passes!

**Comment by hannesvdvreken** [comment]
There ya go: https://github.com/hannesvdvreken/guzzle-clockwork/releases/tag/1.2.0
